<ul>
    <li><a href="<?= $this->url(array(
                        'controller' => 'liv1',
                        'action'     => 'faq'
                        ), 
                        'default',true
                    ); 
                 ?>">FAQ</a></li>
    <li><a href="<?= $this->url(array(
                        'controller' => 'liv1',
                        'action'     => 'vistastatica',
                        'pagina'     => 'chisiamo'
                        ), 
                        'default',true
                    ); 
                 ?>">Chi siamo</a></li>
    <li><a href="<?= $this->url(array(
                        'controller' => 'liv1',
                        'action'     => 'vistastatica',
                        'pagina'     => 'pagamenti'
                        ), 
                        'default',true
                    ); 
                 ?>">Info pagamenti</a></li>
    <li><a href="<?= $this->url(array(
                        'controller' => 'liv1',
                        'action'     => 'listaorganizzazioni',
                        ), 
                        'default',true
                    ); 
                 ?>">Organizzazioni</a></li>
    
    <li><a href="<?=$this->url(array(
                'controller' => 'liv1',
                'action' => 'vistastatica',
                'pagina' => 'adesioneorganizzazioni'), 
                'default',true)?>">Adesione organizzazioni</a></li>
</ul>

