<?= $this->doctype() ?>
<html>
    <head>
        <?= $this->headTitle();?>
        <?= $this->headMeta(); ?>
        <?= $this->headScript();?>
        <?= $this->headLink();?>        
    </head>
    <body> 
        <header>
            
                <?php

                    $ruolo=$this->authInfo('Ruolo');
                    switch ($ruolo) {
                        case 'utente':
                            echo $this->render('navbarliv2.phtml');
                            break;
                    /*    case 'organizzazione':
                            echo $this->render('navbarliv3.phtml');
                            break;
                        case 'admin':
                            echo $this->render('navbarliv4.phtml');
                            break;*/
                        default:
                            echo $this->render('navbar.phtml');
                            break;
                    }
                     
                ?>
            
        </header>
        <div id="contenuto_pagina">
                <?php echo $this->layout()->content; ?>            
        </div>
        <footer id="footer">
            <?= $this->render('footer.phtml') ?>
        </footer>
    </body>
</html>


