<div id="menu">
    <div id="navsx">                        
        <ul>
            <li><a href="<?= $this->url(array(
                        'controller' => 'liv2',
                        'action'     => 'index',
                        ), 
                        'default',true
                    ); 
                 ?>">Home</a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'liv2',
                        'action'     => 'catalogo',
                        ), 
                        'default',true
                    ); 
                 ?>">Eventi</a></li>
        </ul>                    
    </div>
                
    <div id="navdx">
                    
        <ul>
            <li><a href="<?= $this->url(array(
                        'controller' => 'liv2',
                        'action'     => 'ricerca',
                        ), 
                        'default',true
                    ); 
                 ?>"><img id="searchimg" src="<?= $this->baseUrl('css/images/search.png')  ?>" width="30" height="30"></a></li>
            <li><a href="<?= $this->url(array(
                        'controller' => 'liv2',
                        'action'     => 'areaprivata'                           
                        ), 
                        'default',true
                    ); 
                 ?>">Area Privata</a></li>
                                
        </ul>
                    
    </div>
</div>



