<h1> Ciao, <?=$this->AuthInfo('Nome').' '.$this->AuthInfo('Cognome')?>! </h1>
<a href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'listautenti',),
                'default',true
                );?>">Gestione Utenti</a>

<br>
<a href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'listaorganizzazioni',),
                'default',true
                );?>">Gestione Organizzazioni</a>
