<section id="contenuto_centrale">
    <?php if(!is_null($this->messages)):?>
        <?php foreach ($this->messages as $messaggio): ?>
            <div class="messaggio_positivo">
                <?=$messaggio;?>
            </div>
        <?php endforeach;?>
    <?php endif;?>
   
    <h1>Area privata Admin: <?=$this->AuthInfo('Nome').' '.$this->AuthInfo('Cognome')?> </h1>
    <a class="pulsante" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'gestionetipo',),
                'default',true
                );?>">Gestione Tipologie Eventi</a>
    <br>
    <a class="pulsante" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'gestionefaq',),
                'default',true
                );?>">Gestione FAQ</a>
  <br>
  <a class="pulsante" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'listautenti',),
                'default',true
                );?>">Gestione Utenti</a>

<br>
<a class="pulsante" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'listaorganizzazioni',),
                'default',true
                );?>">Gestione Organizzazioni</a>
    

</section>