<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    $(".cancellazione").click(function (event){
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>

<section id="contenuto_centrale">
    <h1>Lista FAQ</h1>
    <table cellpadding="0" cellspacing="0" width="90%">
     <?php foreach ($this->listafaq as $faq) :?>
        <tr><td width="75%"> <h3> <?= $faq->Domanda?> </h3> </td>
            <td rowspan="2" style="background-color: #ffffff; text-align: center"> <a href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'modfaq',
                'faq'=>$faq->Id),
                'default',true
                    );?>">Modifica</a> </td>
            <td rowspan="2" style="background-color: #ffffff; text-align: center"><a class="cancellazione" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'cancellafaq',
                'faq'=>$faq->Id),
                'default',true
                    );?>">Cancella</a></td> </tr>
        <tr><td   ><p> <?= $faq->Risposta?> </p></td></tr>
        
     <?php endforeach;?>
    </table>
</section>
<section id="contenuto_laterale">
    <h1>Altre funzioni</h1>
    <a class="pulsante" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'insfaq'),
                
                'default',true
            );?>">Inserisci nuova FAQ </a>
  
</section>
    <?php if($this->listafaq instanceof Zend_Paginator){
            echo $this->paginationControl($this->listafaq,'Sliding','liv4/_paginatorfaq.phtml');
        } ?>

