<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    $(".cancellazione").click(function (event){
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>
<section id="contenuto_centrale">
    <h1>Lista tipologie</h1>
    <table cellpadding="5" cellspacing="5">
       
        <?php foreach ($this->tipologie as $tipologie): ?>
        <tr><td><?=$tipologie->Nome?></td>
            <td><a href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'modificatipo',
                'tipo' => $tipologie->Nome),
                'default',true
                );?>">Modifica</a></td>
            <td><a class="cancellazione" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'cancellatipologia',
                'tipo' => $tipologie->Nome),
                'default',true
                );?>">Cancella</a>
        </tr>
        <?php endforeach;?>
    </table>
</section>
<section id="contenuto_laterale">
    <h1>Altre funzioni</h1>
    <a class="pulsante" href="<?= $this->url(array(
                'controller' => 'liv4',
                'action' => 'instipologia'),
                'default',true
                );?>">Inserisci nuova tipologia</a>
</section>
