<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    var actionUrl='<?= $this->url(array('controller' => 'liv4', 'action' => 'validazioneform', 'form' => 'insorg',), 'default', true);  ?>';
    var formName='<?= $this->inserisciForm->getName() ?>';
    $(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
    $(":submit").click(function (event){
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>
<section id="contenuto_centrale">
 <h3>Inserisci una nuova organizzazione</h3>
 <?php echo $this->inserisciForm ?>
</section>
