<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    $(":submit").click(function (event){
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>
<h1> Vuoi acquistare questo biglietto? </h1>
<?php if(!is_null($this->evento)) echo '<h2>'.$this->evento->Nome.'</h2>';?>
<h3>Totale: <div id="totale_ordine"><?=$this->evento->ottieniPrezzo()?></div>€</h3> 
<?=$this->formAcquisto;?>