<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    var actionUrl='<?= $this->url(array('controller' => 'liv2', 'action' => 'validazionemodificadati',), 'default', true);  ?>';
    var formName='<?= $this->modForm->getName() ?>';
    $(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
    $(":submit").click(function (event){
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>

<section id="contenuto_centrale">
 <h3>I tuoi dati utente</h3>
 <p>Utilizza questa form per modificare i tuoi dati</p>
 <?php echo $this->modForm ?>
</section>
