<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    $(":submit").click(function (event){
        $("#contenuto_centrale h3").html('submit');
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>

<section id="contenuto_centrale">
 <h3>I tuoi dati utente</h3>
 <p>Utilizza questa form per modificare i tuoi dati</p>
 <?php echo $this->modForm ?>
</section>
