<h1>Lista ordini effettuati</h1>
<?php foreach ($this->ordini as $ordine): ?>
<div class="ordine">
    Evento: <a href="<?= $this->url(array(
                        'controller' => 'liv1',
                        'action'     => 'catalogo',
                        'evento' => $ordine->Evento,
                        ), 
                        'default',true
                    ); 
                 ?>"><?=$this->nomi_eventi[$ordine->Evento]?></a><br>
    Data e ora: <?=$ordine->Data_Ora?><br>
    Numero di biglietti acquistati: <?=$ordine->Numero_Biglietti?><br>
    Modalità di pagamento: <?=$ordine->Modalita_Pagamento?>
</div>
<?php endforeach;?>
<?php if($this->ordini instanceof Zend_Paginator) {
        echo $this->paginationControl($this->ordini,'Sliding','liv2/_paginatorstorico.phtml');
        }  ?>

