<section id="contenuto_centrale">
                <h1>Informazioni per l'adesione delle organizzazioni al sito</h1>
                <p>L'adesione delle organizzazioni non può essere fatta in modo autonomo per problemi di veridicità delle organizzazioni. Per questo motivo sarà direttamente l'amministratore del sito ad iscrivere le aziende organizzatrici di eventi.</p>
                <p>Aderire al sito è molto semplice: è necessario inviare un email all'amministratore del sito, con i dati personali dell'azienda(nome, sede, contatti vari ...). Alla conclusione dell’istruttoria, l'amministratore invierà una nuova mail all'inidirizzo di posta elettronica precedentemente comunicato.
                  Nel caso di avvenuta iscrizione saranno comunicate via email le credenziali iniziali di accesso al sito, ovvero username e password. <b>Si consiglia un immediato cambiamento delle credenziali di accesso.</b></p>
                <p>L'amministratore si riserva la decisione di iscrizione o meno delle aziende organizzatrici.</p>
                <p>Indirizzo di posta elettronica a cui fare richiesta: <b>admin@gmail.com</b></p>
</section>

