<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/script.js'))
	->captureStart() ?>


$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'liv1', 'action' => 'filtroajax',), 'default',true);  ?>';
	var formName='<?= $this->filtroForm->getName() ?>';
	$(":input").on('change', function(event) {
            $(this).closest("body").find(".pagination").hide();
            submitAjax(actionUrl,formName);
        });
});

<?php $this->headScript()->captureEnd() ?>

<?php if (is_null($this->EvSelezionato)):?>
    <section id="contenuto_top">
        <?= $this->filtroForm; ?>
    </section>
<?php endif;?>
<section id="contenuto_centrale">
<?php
        $evento=$this->eventi;
        $ruolo=$this->authInfo('Ruolo');
        $utente=$this->authInfo('Username');
        if (!is_null($this->EvSelezionato))  //visualizzazione evento singolo
        {
            echo $this->AnteprimaEvento($this->eventi,'singolo',$this->numpart );
            
            if($ruolo=='liv2'){ //modificare per rendere visibile su tutti i livelli tranne liv1 es: !is_null($ruolo)
                   
                if (!$evento->acquistabile()) {
                    echo '<div class="messaggio_importante">I biglietti non sono più acquistabili</div>';
                }
                else if ($evento->Biglietti_Rimanenti==0){
                    echo '<div class="messaggio_importante">I biglietti sono terminati</div>';
                }
                else{
                    echo '<div class="tasto_acquisto"><a href="'.$this->url(array(
                                                        'controller' => 'liv2',
                                                        'action' => 'checkout',
                                                        'evento' => $this->eventi->Id),
                                                        'default',true
                                                        ).'">Acquista</a></div>';}
                }
                
                echo '<div style="clear:both;"></div>';
                echo '<h3>Luogo evento</h3>';
                echo $evento->Mappa;
        }
         else if (!is_null($this->eventi))
        {
            echo '<h1>Lista eventi</h1>';
            echo '<ul id="listaeventi">';
            $count=0;
            foreach ($this->eventi as $evento){
                echo $this->AnteprimaEvento($evento,'anteprima');
                $count++;
            }
            if($count==0){
                echo '<h2>Non ci sono eventi che corrispondono ai parametri di ricerca</h2>';
            }
            echo '</ul>';
            
        }



        if($this->eventi instanceof Zend_Paginator) {
        echo $this->paginationControl($this->eventi,'Sliding','liv1/_paginatoreventicatalogo.phtml');
        }
        ?>
</section>
<?php if (is_null($this->EvSelezionato)):?>
    <section id="contenuto_laterale">    
            <h1> Categorie </h1>
            <ul>
                <?php foreach ($this->cat as $cat): ?>
                    <li> <a href="<?= $this->url(array(
                            'controller' => 'liv1',
                            'action' => 'catalogo',
                            'SelCat' => $cat->Nome),
                            'default',true
                            );?>"><?= $cat->Nome ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>

    </section>
<?php endif;?>
<?php if(($ruolo=='liv2' || $ruolo == null) && !is_null($this->EvSelezionato)): ?>
    <section id="contenuto_laterale">
            <h1>Utenti che parteciperanno</h1>
            <div class="partecipazione_div">
            <?php if(!$this->partecipato && $ruolo=='liv2' && $evento->acquistabile()):?>
                <div class="tasto_partecipazione">
                    <a href="<?=$this->url(array(
                        'controller' => 'liv2',
                        'action' => 'partecipazione',
                        'evento' => $this->eventi->Id),
                        'default', true)?>"> Parteciperò </a>
                </div>
            <?php else: ?>
                <div class="tasto_partecipazione">
                    <div>Parteciperò</div>
                </div>
            <?php endif;?>
                <div class="numero_partecipazione">
                    <?=$this->numpart?>
                </div>
            </div>
    </section>
<?php endif;?>
