<section id="contenuto_top">
    <?php 
    if (is_null($this->EvSelezionato)){
        echo $this->filtroForm; }
    ?>    
</section>
<section id="contenuto_centrale">
<?php 
       
        if (!is_null($this->EvSelezionato))
        {
            echo $this->AnteprimaEvento($this->eventi,'singolo');
        } else if (!is_null($this->eventi))
        {
            echo '<h1>Lista eventi</h1>';
            echo '<ul id="listaeventi">';
            $count=0;
            foreach ($this->eventi as $evento){
                echo $this->AnteprimaEvento($evento,'anteprima');
                $count++;
            }
            echo '</ul>';
            if($count==0){
                echo '<h2>Non ci sono eventi che corrispondono ai parametri di ricerca</h2>';
            }
        }
        
        
    
        if($this->eventi instanceof Zend_Paginator) {
        echo $this->paginationControl($this->eventi,'Sliding','liv1/_paginatoreventicatalogo.phtml');
        } 
        ?> 
</section>   
