<section id="contenuto_centrale">
                <h1>Chi siamo?</h1>
                <p><b>TecWeb07 : Biglietteria e marketing al servizio dell’entertainment</b></p>
<p>TecWeb07 è la più importante società italiana nel settore dei servizi integrati di biglietteria,
    e-commerce e marketing per musica, spettacolo sport e cultura.</p>
<p>Le sue attività si rivolgono al Grande pubblico, agli organizzatori di eventi e alle aziende:</p>
<p><b>Per il pubblico:</b></p>
<p>TecWeb07 è il punto di riferimento per il tempo libero e per l’acquisto di biglietti di tutti 
    i più grandi eventi che si svolgono in Italia ed i principali all’estero.</p>
<p><b>Per gli organizzatori di eventi:</b></p>
<p>TecWeb07 è il Partner ideale di società sportive, musei, teatri, parchi, organizzatori di concerti/eventi
    ai quali fornisce avanzati sistemi computerizzati per la gestione della biglietteria,
    integrati con moderni sistemi di controllo degli accessi.
    I software di biglietteria sono veloci, flessibili, modulari ed in grado di soddisfare tutte le esigenze
    di ticketing e di amministrazione/rendicontazione di chi organizza un evento.
    L’integrazione con il controllo degli accessi può avvenire attraverso dispositivi diversi: tornelli,
    colonnine, lettori palmari in grado di leggere il titolo e validare o meno l’ingresso degli spettatori.</p>
<p>TecWeb07 è uno strumento valido per promuovere gli eventi, grazie alla forza dei propri canali di vendita
    web. Inoltre, sono molti gli spazi di promozione e comunicazione che i partner di TecWeb07
    (grandi aziende e media tradizionali) riservano agli eventi.</p>
<p><b>Per le Aziende</b></p>
<p>Un concerto, uno spettacolo teatrale, una mostra, una partita di calcio sono opportunità straordinarie 
    per comunicare!</p>
<p>TecWeb07 offre servizi esclusivi e vantaggi alle aziende partner che vogliono fare comunicazione 
    attraverso il mondo dell’entertainment.
    Aiuta a fidelizzare la clientela delle aziende partner e a coinvolgere nuovi target offrendo loro canali
    riservati di accesso alla biglietteria degli eventi o servizi a valore aggiunto.</p>
  <h1>Dove siamo</h1>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1239.424176457322!2d13.516078081943599!3d43.58761350058858!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x161719e4f3f5daaf!2sUniversit%C3%A0+Politecnica+delle+Marche+-+Facolt%C3%A0+di+Ingegneria!5e0!3m2!1sit!2sus!4v1526404108922" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</section>
