<section id="contenuto_centrale">
                <h1>Chi siamo?</h1>
                <div>Siamo fatti della materia di cui son fatti i sogni; e nello spazio e nel tempo d’un sogno è racchiusa la nostra breve vita.
(La tempesta)

Quando non sarai più parte di me ritaglierò dal tuo ricordo tante piccole stelle, allora il cielo sarà così bello
che tutto il mondo si innamorerà della notte.
(Romeo e Giulietta)

Il pazzo, l’amante e il poeta non sono composti che di fantasia.
(Sogno di una notte di mezza estate)

Ama, ama follemente, ama più che puoi e se ti dicono che è peccato ama il tuo peccato e sarai innocente.
(Romeo e Giulietta)

Rinuncia al tuo potere di attrarmi ed io rinuncerò alla mia volontà di seguirti.
(Sogno di una notte di mezza estate)

Non desidero una rosa a Natale più di quanto possa desiderar la neve a maggio: d’ogni cosa mi piace che maturi quand’è la sua stagione.
(Pene d’amore perdute)</div>
</section>