<div id="contenuto_centrale">
    <?php if(is_null($this->selectedOrg)) {
        echo '<h1>Le nostre organizzazioni</h1>';
        echo '<ul id="listaorg">';
        foreach ($this->organizzazioni as $organiz) {
            echo '<li class="org_li"><a href='.$this->url(array('controller' => 'liv1','action' => 'listaorganizzazioni','organizzazione' => $organiz->Id), 'default',true).'><div class="org_sfondo"><div class="org_logo">'.$organiz->Logo.'</div><div class="org_nome">'.$organiz->Nome.'</div></div></a></li>';
        }
    } else {
        echo '<div id="SingolaOrganizzazione"><div>'.$this->organizzazioni->Logo.'</div><div> Nome: '.$this->organizzazioni->Nome.'</div><br><div> Sede: '.$this->organizzazioni->Sede.'</div><br><div> Email: '.$this->organizzazioni->Email.'</div><div> Telefono: '.$this->organizzazioni->Telefono.'</div><div> Fax: '.$this->organizzazioni->Fax.'</div><br><div> Missione: '.$this->organizzazioni->Missione.'</div><br><div> Descrizione: '.$this->organizzazioni->Descrizione.'</div></div>';
    }
       
    if($this->organizzazioni instanceof Zend_Paginator) {
        echo $this->paginationControl($this->organizzazioni,'Sliding','liv1/_paginatororganizzazioni.phtml');
    } 
    ?>
</div> /

