<section id="contenuto_centrale">
                <h1>Info sui pagamenti</h1>
                <p> I metodi di pagamento  sono: <ol>
                    <li>Master Card</li>
                    <li>Visa</li>
                    <li>PayPal</li>
                    <li>Bonifico bancario SEPA</li>
                </ol></p>
                <p><b>Il pagamento con bonifico</b></p>
                <p>Il bonifico necessita in genere di 4-5 giorni prima che venga rilevato dal sistema. Non è necessario che ci contatti per segnalare il pagamento, il rilevamento è automatico, trascorsi i 5 giorni non visualizzerai più il promemoria di pagamento all'accesso al tuo sito.</p>
                <p><b>La fattura per il mio acquisto</b></p>
                <p>La fattura è scaricabile subito dopo aver concluso l'ordine, nell'ultima schermata.</p>
</section>
