<section id="contenuto_centrale">
                <h1>Info sui pagamenti</h1>
                <div>Aenean velit libero, molestie a lorem at, dignissim blandit arcu. Donec nisi dui, mattis at mi pretium, vehicula elementum arcu. Aenean a luctus mauris. Quisque imperdiet tempor tellus quis condimentum. Pellentesque sagittis urna sed elit auctor, at ultricies erat vulputate. Nunc eu egestas augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut scelerisque erat urna, a egestas quam mollis ut. In rhoncus nunc quis arcu cursus, ut pretium sem pulvinar. Pellentesque non ex facilisis, tristique tortor ac, varius lectus. Morbi sollicitudin lorem tortor, ut tempus ex interdum nec. Nullam sit amet libero non massa imperdiet euismod. Curabitur in blandit nibh. Mauris fringilla pellentesque ex.

</div>
            </section>