<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/script.js'))
	->captureStart() ?>

$(function()
{
    var actionUrl='<?= $this->url(array('controller' => 'liv1', 'action' => 'validazioneregistrazione',), 'default', true);  ?>';
    var formName='<?= $this->regForm->getName() ?>';
    $(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
    $(":submit").click(function (event){
        return confirm("Confermi?");
    });
});

<?php $this->headScript()->captureEnd() ?>
<section id="contenuto_centrale">
 <h3>Registrati</h3>
 <p>Utilizza questa form per registrarti nel sito</p>
 <?php echo $this->regForm ?>
</section>
