<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    var actionUrl='<?= $this->url(array('controller' => 'liv3', 'action' => 'validazioneinserimento',), 'default', true);  ?>';
    var formName='<?= $this->formInserimento->getName() ?>';
    $(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
    $(":submit").click(function (event){
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>
<section id="contenuto_centrale">
    <h1>Inserisci un nuovo evento</h1>
    <?= $this->formInserimento; ?>
</section>

