<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->captureStart() ?>
$(function()
{
    var actionUrl='<?= $this->url(array('controller' => 'liv3', 'action' => 'validazionemodifica',), 'default');  ?>';
    var formName='<?= $this->formModifica->getName() ?>';
    $(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
    $(":submit").click(function (event){
        return confirm("Confermi?");
    });
});
<?php $this->headScript()->captureEnd() ?>
<section id="contenuto_centrale">
    <h1>Modifica i dati dell'evento</h1>
    <?= $this->formModifica; ?>
    <div><a class="tasto_cancella cancellazione" href="<?= $this->url(array(
                'controller' => 'liv3',
                'action' => 'cancella',
                'evento' => $this->idevento),
                'default',true
                );?>">Cancella Evento</a></div>
</section>

